### PR TITLE
Fixed wave color, now not only white

### PR DESCRIPTION
**Pull request by maximbilan**
Fixed wave color, now you can set up color, which you want.
self.waveColor is never used...
Thanks.

### CODE REVIEW

**Comment by cakl** [comment]
+1, please merge!

**Comment by maximbilan** [comment]
<b>cak</b>l, you can use this <a href="https://github.com/maximbilan/Waver">fork</a>.

**Comment by cakl** [comment]
thx. @maximbilan, I'm already doing this. But a merge by @kevinzhow would be nice anyway...

**Comment by maximbilan** [comment]
@cakl, I agree with you, would be great:)

**Comment by cakl** [comment]
@maximbilan Do you know why there's a difference in the height of the amplitude if you render it with initWithFrame and initWithCoder (storyboard)? I don't know how to fix this bug

**Comment by maximbilan** [comment]
@cakl I think that you need to override the <b>initWithCoder</b> method and call the <b>setup</b> method there, how it makes <b>initWithFrame</b> method.
screen shot 2015-04-15 at 10 58 57 pm

**Comment by cakl** [comment]
thats already done with the ```awakeFromNib``` method. But the height of the amplitude is nearly the double

**Pull request merged**
